"""empty message

Revision ID: 9e7278e93e1b
Revises: 16ed64eff1b4
Create Date: 2025-07-14 12:29:42.650046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7278e93e1b'
down_revision = '16ed64eff1b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sobrenome', sa.String(), nullable=True))
        batch_op.drop_column('sobremone')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sobremone', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('sobrenome')

    # ### end Alembic commands ###
